export const routePaths = {
  root: '/',
  login: '/login',
  dashboard: '/dashboard',
  students: '/students',
  staff: '/staff',
  admission: '/admission',
  attendance: '/attendance',
  scholarships: '/scholarships',
  invoices: '/invoices',
  payments: '/payments',
  settings: '/settings',
  notifications: '/notifications',
  transferCertificate: '/transfer-certificate',
  feeStructure: '/fee-structure',
  reports: '/reports',
  userCreation: '/user-creation',
};
