export const routePaths = {
  root: '/',
  login: '/login',
  loginOtp: '/login/verify-otp',
  firstLoginChangePassword: '/first-login/change-password',
  forgotPassword: '/forgot-password',
  forgotPasswordOtp: '/forgot-password/verify-otp',
  resetPassword: '/forgot-password/reset',
  dashboard: '/dashboard',
  students: '/students',
  staff: '/staff',
  admission: '/admission',
  attendance: '/attendance',
  scholarships: '/scholarships',
  invoices: '/invoices',
  payments: '/payments',
  settings: '/settings',
  notifications: '/notifications',
  transferCertificate: '/transfer-certificate',
  feeHead: '/fee-head',
  feeStructure: '/fee-structure',
  reports: '/reports',
  userCreation: '/user-creation',
  bulkUpload: '/bulk-upload',
};
